@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctcmVwb3J0Iiwic3ViIjoiYWRtaW4iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjczNDY2Mzg2fQ.EnWYvVdBHBhPuFFYCE7qzzWEyfaVEL7jrmKGHzDEMvo

###

POST {{url}}/api/authenticate HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "root"
}

###

GET {{url}}/api/reports
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/incomplete
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/author
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/voted
Authorization: Bearer {{token}}


###

POST {{url}}/api/reports/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Testing",
    "issueDescription": "Testing",
    "replicationInstructions": "1, 2, 3",
    "postDate": "2022-03-11",
    "completionStatus": false,
    "authorUsername": "test"
  }

###

PUT {{url}}/api/reports/update/4/true
Authorization: Bearer {{token}}

###

POST {{url}}/api/vote/4
Authorization: Bearer {{token}}


###

DELETE {{url}}/api/vote/4
Authorization: Bearer {{token}}


###

GET {{url}}/api/vote/check/1
Authorization: Bearer {{token}}

###

GET {{url}}/api/users
Authorization: Bearer {{token}}

###

GET {{url}}/api/messages/2

###

POST {{url}}/api/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "message": "Testing 2",
    "postDate": "2022-03-11",
    "authorUsername": "admin",
    "reportId": 2
}

###

DELETE {{url}}/api/messages/1
Authorization: Bearer {{token}}


###