@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctcmVwb3J0Iiwic3ViIjoidGVzdCIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTY3MzIxMTEwMn0.5X8n7Nf5CaG0F5HwRiGO86QEPGUldWP6j_N2fJTvPbE

###

POST {{url}}/api/authenticate HTTP/1.1
content-type: application/json

{
  "username": "test",
  "password": "test"
}

###

GET {{url}}/api/reports
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/incomplete
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/author
Authorization: Bearer {{token}}


###

GET {{url}}/api/reports/voted
Authorization: Bearer {{token}}


###

POST {{url}}/api/reports/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Testing",
    "issueDescription": "Testing",
    "replicationInstructions": "1, 2, 3",
    "postDate": "2022-03-11",
    "completionStatus": false,
    "authorUsername": "test"
  }

###

PUT {{url}}/api/reports/update/4/true
Authorization: Bearer {{token}}

###

POST {{url}}/api/vote/4
Authorization: Bearer {{token}}


###

DELETE {{url}}/api/vote/4
Authorization: Bearer {{token}}


###